//! GL call forensics.
//!
//! When a guest app observes a GL error (typically via its own `glGetError`,
//! where the error was actually generated by an earlier call — possibly
//! host-internal EAGL/CA work), a bare `0x502` tells you nothing. This module
//! keeps a per-thread ring buffer of the most recent GL operations (guest
//! wrapper calls and host-internal GL work) and, on error, emits a forensic
//! report: the ring (call sequence + which op first reported the error), the
//! full GL state at that moment (bindings, viewport, enabled caps, FBO
//! completeness), the calling thread, and the active host function.
//!
//! Recording is designed to be safe to leave always-on: no allocation in the
//! hot path (fixed-capacity ring, interned static name slices), the only
//! Strings are built when an optional args capture is provided (a handful of
//! strategically instrumented wrappers), and the report itself is
//! rate-limited per error code so a 500-error storm costs at most a couple of
//! reports per second.

use std::cell::RefCell;
use std::collections::HashMap;
use std::fmt::Write as _;

use crate::gles::gles11_raw as gles11; // constants only
use crate::gles::GLES;

/// Ring capacity: enough to cover a full guest frame of GL work.
const RING_SIZE: usize = 96;

/// Max characters kept for a single args capture.
const ARGS_MAX: usize = 160;

/// One recorded GL operation.
struct GlOp {
    /// Monotonic operation counter (per thread).
    gen: u64,
    /// Operation name, e.g. `glBindFramebuffer` or `host:EAGL-present`.
    name: &'static str,
    /// Optional truncated args dump (only for instrumented wrappers).
    args: Option<String>,
    /// Error observed immediately after this op (0 = clean/unknown).
    err: u32,
}

thread_local! {
    static RING: RefCell<Ring> = RefCell::new(Ring::default());
}

#[derive(Default)]
struct Ring {
    ops: std::collections::VecDeque<GlOp>,
    gen: u64,
    /// How many times each error code has been reported from this thread.
    reported: HashMap<u32, u32>,
}

impl Ring {
    fn push(&mut self, name: &'static str, args: Option<String>, err: u32) {
        self.gen += 1;
        if self.ops.len() == RING_SIZE {
            self.ops.pop_front();
        }
        self.ops.push_back(GlOp {
            gen: self.gen,
            name,
            args,
            err,
        });
    }
}

/// Intern a dynamically-produced operation name (e.g. the active host
/// function name) into a `&'static str` so the ring never allocates per
/// record. The set of distinct names is tiny (bounded by the number of host
/// functions), so interning by leak is bounded.
fn intern_name(name: &str) -> &'static str {
    thread_local! {
        static INTERNED: RefCell<HashMap<String, &'static str>> = RefCell::new(HashMap::new());
    }
    INTERNED.with(|cache| {
        if let Some(interned) = cache.borrow().get(name) {
            return *interned;
        }
        let leaked: &'static str = Box::leak(name.to_string().into_boxed_str());
        cache.borrow_mut().insert(name.to_string(), leaked);
        leaked
    })
}

/// Record a GL operation that just completed. `name` is the operation name
/// when known (the active host function, or `host:…` for internal work);
/// `err` is the error observed right after the op (0 when clean/unknown).
/// Never allocates in the hot path.
pub fn record(name: Option<&str>, err: u32) {
    let name = match name {
        Some(name) => intern_name(name),
        None => "unknown-gl-op",
    };
    record_static(name, None, err);
}

/// Record with an explicit static name (used by host-internal sites and
/// instrumented wrappers with args captures).
pub fn record_named(name: &'static str, args: Option<String>, err: u32) {
    record_static(name, args, err);
}

fn record_static(name: &'static str, args: Option<String>, err: u32) {
    RING.with(|r| {
        r.borrow_mut().push(name, args, err);
    });
}

/// Record a host-internal GL operation (EAGL present, CA compositor, …).
pub fn record_host(name: &'static str) {
    record_static(name, None, 0);
}

/// Truncate and format an args capture.
pub fn fmt_args(args: std::fmt::Arguments) -> String {
    let mut s = args.to_string();
    if s.len() > ARGS_MAX {
        let mut cut = ARGS_MAX;
        while !s.is_char_boundary(cut) {
            cut -= 1;
        }
        s.truncate(cut);
        s.push('…');
    }
    s
}

/// How frequently a full forensic report is emitted per error code per thread.
const REPORT_EVERY: u32 = 50;

/// Should a full report be emitted for this error right now? Keeps a per-code
/// counter so the first occurrence always reports immediately.
fn should_report(err: u32) -> bool {
    RING.with(|r| {
        let mut ring = r.borrow_mut();
        let count = ring.reported.entry(err).or_insert(0);
        *count += 1;
        *count == 1 || *count % REPORT_EVERY as u32 == 0
    })
}

fn gl_error_name(err: u32) -> &'static str {
    match err {
        0x0500 => "GL_INVALID_ENUM",
        0x0501 => "GL_INVALID_VALUE",
        0x0502 => "GL_INVALID_OPERATION",
        0x0503 => "GL_STACK_OVERFLOW",
        0x0504 => "GL_STACK_UNDERFLOW",
        0x0505 => "GL_OUT_OF_MEMORY",
        0x0506 => "GL_INVALID_FRAMEBUFFER_OPERATION",
        0x0507 => "GL_CONTEXT_LOST",
        _ => "unknown-error",
    }
}

fn fb_status_name(status: u32) -> &'static str {
    match status {
        0x8CD5 => "GL_FRAMEBUFFER_COMPLETE",
        0x8CD6 => "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT",
        0x8CD7 => "GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT",
        0x8CD8 => "GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS",
        0x8CD9 => "GL_FRAMEBUFFER_UNSUPPORTED",
        0x8CAA => "GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE",
        _ => "unknown-status",
    }
}

/// Dump the live GL state relevant to framebuffer/render errors. Queries run
/// through the same backend the guest uses. Any error the probes themselves
/// generate is drained at the end (noted in the dump).
fn dump_gl_state(gles: &mut dyn GLES, out: &mut String) {
    fn query_int(gles: &mut dyn GLES, out: &mut String, label: &str, pname: u32) -> Option<i32> {
        let mut value = [0i32];
        unsafe { gles.GetIntegerv(pname, value.as_mut_ptr()) };
        let _ = writeln!(out, "  {} = {}", label, value[0]);
        Some(value[0])
    };
    let _ = writeln!(out, "GL state at error time:");
    let viewport = query_int(gles, out, "GL_VIEWPORT", gles11::VIEWPORT);
    let fbo = query_int(
        gles,
        out,
        "GL_FRAMEBUFFER_BINDING",
        gles11::FRAMEBUFFER_BINDING_OES,
    );
    query_int(
        gles,
        out,
        "GL_RENDERBUFFER_BINDING",
        gles11::RENDERBUFFER_BINDING_OES,
    );
    query_int(
        gles,
        out,
        "GL_ARRAY_BUFFER_BINDING",
        gles11::ARRAY_BUFFER_BINDING,
    );
    query_int(
        gles,
        out,
        "GL_ELEMENT_ARRAY_BUFFER_BINDING",
        gles11::ELEMENT_ARRAY_BUFFER_BINDING,
    );
    query_int(
        gles,
        out,
        "GL_TEXTURE_BINDING_2D",
        gles11::TEXTURE_BINDING_2D,
    );
    query_int(gles, out, "GL_ACTIVE_TEXTURE", gles11::ACTIVE_TEXTURE);
    // Enabled caps that commonly cause INVALID_OPERATION when mismatched.
    for (label, cap) in [
        ("GL_DEPTH_TEST", gles11::DEPTH_TEST),
        ("GL_STENCIL_TEST", gles11::STENCIL_TEST),
        ("GL_BLEND", gles11::BLEND),
        ("GL_SCISSOR_TEST", gles11::SCISSOR_TEST),
        ("GL_CULL_FACE", gles11::CULL_FACE),
    ] {
        let enabled = unsafe { gles.IsEnabled(cap) };
        let _ = writeln!(out, "  {} = {}", label, enabled != 0);
    }
    // Framebuffer completeness of the bound FBO (may itself log; drained).
    if let Some(fbo) = fbo {
        if fbo != 0 {
            let status = unsafe { gles.CheckFramebufferStatusOES(0x8D40) };
            let _ = writeln!(
                out,
                "  bound FBO {} status = {:#x} ({})",
                fbo,
                status,
                fb_status_name(status)
            );
        }
    }
    let _ = viewport;
    // Drain any errors the state probes generated so the guest's own error
    // stream is not polluted by diagnostics.
    let mut probe_errors = 0;
    while unsafe { gles.GetError() } != 0 {
        probe_errors += 1;
        if probe_errors > 8 {
            break;
        }
    }
    if probe_errors != 0 {
        let _ = writeln!(
            out,
            "  ({} error(s) generated by the state probes themselves were drained)",
            probe_errors
        );
    }
}

/// Build the multi-line forensic report for `err`. `function` names the guest
/// host function active when the error was observed; `caller` identifies the
/// wrapper the error surfaced through.
pub fn report(
    gles: &mut dyn GLES,
    err: u32,
    function: Option<&str>,
    caller: &'static std::panic::Location<'static>,
) -> bool {
    if err == 0 || !should_report(err) {
        return false;
    }
    let mut out = String::with_capacity(4096);
    let _ = writeln!(
        out,
        "[GLES FORENSICS] error 0x{:04x} ({}) observed at {}:{} (active host function: {})",
        err,
        gl_error_name(err),
        caller.file(),
        caller.line(),
        function.unwrap_or("unknown"),
    );
    let _ = writeln!(
        out,
        "[GLES FORENSICS] last {} GL ops on thread {:?} (gen | name | err | args):",
        RING.with(|r| r.borrow().ops.len()),
        std::thread::current().id(),
    );
    RING.with(|r| {
        let ring = r.borrow();
        for op in &ring.ops {
            let marker = if op.err == err && err != 0 {
                "  <-- FIRST ERROR HERE?"
            } else {
                ""
            };
            let _ = writeln!(
                out,
                "[GLES FORENSICS]   {:>6} | {:<28} | 0x{:04x} | {}{}",
                op.gen,
                op.name,
                op.err,
                op.args.as_deref().unwrap_or(""),
                marker,
            );
        }
    });
    dump_gl_state(gles, &mut out);
    crate::log::echo_preformatted(&out);
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ring_records_and_caps() {
        record_named("test-op-a", None, 0);
        record_named("test-op-b", Some(fmt_args(format_args!("x={} y={}", 1, 2))), 0x502);
        RING.with(|r| {
            let ring = r.borrow();
            assert!(ring.ops.len() <= RING_SIZE);
            let last = ring.ops.back().unwrap();
            assert_eq!(last.name, "test-op-b");
            assert_eq!(last.args.as_deref(), Some("x=1 y=2"));
            assert_eq!(last.err, 0x502);
        });
    }

    #[test]
    fn first_error_always_reports() {
        // Fresh thread-local state on the test thread: first report goes out.
        assert!(should_report(0xDEAD));
        // Subsequent ones are rate-limited.
        assert!(!should_report(0xDEAD));
        // A different code reports immediately again.
        assert!(should_report(0xBEEF));
    }

    #[test]
    fn args_are_truncated() {
        let big = "A".repeat(1000);
        let s = fmt_args(format_args!("{}", big));
        assert_eq!(s.len(), ARGS_MAX + '…'.len_utf8());
        assert!(s.ends_with('…'));
    }

    #[test]
    fn dynamic_names_are_interned() {
        let a = intern_name("glFoo");
        let b = intern_name("glFoo");
        assert_eq!(a, b);
        assert_eq!(a, "glFoo");
    }
}
